### ISSUE TITLE
Issue parsing SELECT statement with database

### ISSUE THREAD

**Issue by wapacro** [crodas/SQLParser#1]
Hi

Thanks for your work. I ran across an error when i tried to parse a SELECT statement which contains the database name.

`SELECT myAttribute FROM myDatabase.myTable;`
_Illegal offset type vendor\crodas\sql-parser\src\SQL\Select.php on line 50_

Would be nice if you could take a look at it.

**Comment by crodas** [comment]
Thank you for your report, I'll work on fixing the issue you reported.

**Comment by crodas** [comment]
Fixed in #3.
