### ISSUE TITLE
Some important bugs

### ISSUE THREAD

**Issue by BrooktecDeveloper** [crodas/SQLParser#2]
- IS and IS NOT are treated and translated as = and !=, but x IS NULL is not the same as x = NULL
- OR and AND statements are parsed with equal precedence, though AND must have more precedence (maybe it is the problem with many more operators
- Parenthesis dissapear when writting the query

**Comment by crodas** [comment]
Thank you for your report, I'll work on fixing the issues you reported.

**Comment by crodas** [comment]
@BrooktecDeveloper I think I fixed all the issues with #4 and #5. Feel free to reopen this issue otherwise.
